import {
  HomePage,
  LoginPage,
  RegisterPage,
  RestaurantListPage,
  MenuPage,
  CartPage,
  OrderConfirmationPage,
  ProfilePage,
  FoodDetailsPage,
  CheckoutPage,
  OrderStatusPage,
  OrdersPage,
  AboutPage,
  ContactPage,
  ForgotPasswordPage,
  ResetPasswordPage,
  OwnerLoginPage,
  OwnerRegisterPage,
  OwnerDashboardPage,
  AddFoodPage,
  AdminLoginPage,
  NewAdminDashboard,
} from "./pages";